"""empty message

Revision ID: 5ff1d7c117cf
Revises: 5165db9dd43a
Create Date: 2024-03-31 15:46:19.608969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ff1d7c117cf'
down_revision = '5165db9dd43a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_captcha',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('captcha', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True))

    op.drop_table('email_captcha')
    # ### end Alembic commands ###
