"""empty message

Revision ID: 5165db9dd43a
Revises: 65b6d80b5646
Create Date: 2024-03-31 15:34:06.197503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5165db9dd43a'
down_revision = '65b6d80b5646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('captcha', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('captcha')

    # ### end Alembic commands ###
